packages:
  - apps/*
  - packages/*
  - tests/*

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  cpu-features: false
  esbuild: true
  prisma: true
  protobufjs: false
  ssh2: false
